coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        # advanced settings
        branches: null
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate 